@MindSharper.API_HostAddress = http://localhost:5273

GET {{MindSharper.API_HostAddress}}/api/decks/
Accept: application/json

###

GET {{MindSharper.API_HostAddress}}/api/decks/6
Accept: application/json

###

POST {{ MindSharper.API_HostAddress}}/api/decks
Content-Type: application/json

{
  "name": "PowerShell"
}