@MindSharper.API_HostAddress = http://localhost:5273

GET {{MindSharper.API_HostAddress}}/api/decks/
Accept: application/json

###

GET {{MindSharper.API_HostAddress}}/api/decks/1
Accept: application/json

###

POST {{ MindSharper.API_HostAddress}}/api/decks
Content-Type: application/json

{
  "name": "C"
}

###
DELETE {{MindSharper.API_HostAddress}}/api/decks/3

###
PATCH {{MindSharper.API_HostAddress}}/api/decks/name
Content-Type: application/json

{
  "name": "C#",
  "deckId": 1
}