@MindSharper.API_HostAddress = http://localhost:5273

GET {{MindSharper.API_HostAddress}}/api/decks/?pageSize=2&pageNumber=1
Accept: application/json

###

GET {{MindSharper.API_HostAddress}}/api/decks/1
Accept: application/json

###

POST {{ MindSharper.API_HostAddress}}/api/decks
Content-Type: application/json

{
  "name": "JavaScript"
}

###
DELETE {{MindSharper.API_HostAddress}}/api/decks/3

###
PATCH {{MindSharper.API_HostAddress}}/api/decks/name
Content-Type: application/json

{
  "name": "C#",
  "deckId": 1
}

###
GET {{MindSharper.API_HostAddress}}/api/decks/2/flashcards

### 
GET {{MindSharper.API_HostAddress}}/api/decks/1/flashcards/1

###
POST {{ MindSharper.API_HostAddress}}/api/decks/1/flashcards
Content-Type: application/json

{
  "frontside": "Explain keyword 'in'",
  "backside": "1. pass valuetypes by reference (e.g. structs) 2. reference is readonly"
}
